version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: banking_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - banking-network
    ports:
      - "3306:3306"

  springboot:
    image: chaudharipankaj/banking-service-api:jenkins
    container_name: banking-service-container
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8090:8090"
    networks:
      - banking-network
    depends_on:
      - mysql

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    networks:
      - banking-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - banking-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - banking-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - banking-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
     - '3000:3000'
    networks:
      - banking-network

volumes:
  mysql-data:

networks:
  banking-network:
    name: banking-network
